### ISSUE TITLE
Detecing port used by bridge server is too complicated

### ISSUE THREAD

**Issue by potmo** [baudehlo/node-phantom-simple#9]
Right now there is a couple of lines that try to find what port the webserver uses to be able to send messages to it. It starts on [line 94](https://github.com/baudehlo/node-phantom-simple/blob/master/node-phantom-simple.js#L94).
The problem is that it doesn't work correctly and relies on system specific calls external programs. See @Fresa s [pull request](https://github.com/baudehlo/node-phantom-simple/pull/8) for a go at trying to fix some of the issues

I think, contrary to what the node-phantom-simple documentation says, that the webserver module used is not one built into node but the one built in to phantomjs.

If I understand the [phantomjs docs for webserver] (https://github.com/ariya/phantomjs/wiki/API-Reference-WebServer#module-webserver) there should be a `port` field that is exposed on the webserver object.
> port : the port on which the server listen requests (readonly)

That values should be possible to send via stdout from the bridge to the node-phantom-simple module running in the node scope just like the bridge already does to detect if phantomjs is ready (see [line 78](https://github.com/baudehlo/node-phantom-simple/blob/master/node-phantom-simple.js#L78) ).

Does all this make sense? Have I missed somethign? Otherwise I'll have a go at this tomorrow.

**Comment by puzrin** [comment]
I think we can close this ticket. Yes, that peace of code is dirty, but it's the only way to workaround phantomjs bug properly in multiprocess environment.

If you look for [SlimerJS patch](https://github.com/baudehlo/node-phantom-simple/commit/03f758a81f6e4589cd45c8faadd7586aaa32ad98), accepted to master, you will see that appropriate part for slimer is more simple, because it returns correct port value. As side effect - after PhantomJS fix `webserver.port` value, this driver will stop use hacks automatically.

Does anyone has reasons why this ticket should stay open?

**Comment by baudehlo** [comment]
How does slimerjs get the right port, just for my curiosity ? Or has this now been fixed in phantom?

**Comment by puzrin** [comment]
See https://github.com/baudehlo/node-phantom-simple/commit/03f758a81f6e4589cd45c8faadd7586aaa32ad98#diff-b590f93db9bb7894e89e0b023a761e3fR189 . You can read `webserver.port`, and it returns correct value (the real port after listen to `:0`).

That's NOT fixed in phantom < 2.0, and we did not tested 2.0 (because it's beta/buggy/not-released-in-npm-yet).

**Comment by baudehlo** [comment]
No I get that, I just mean that phantom doesn't provide the right port, so how can you get it?

**Comment by puzrin** [comment]
They have completely different implementations. Slimer use wrapper for built-in library https://github.com/laurentj/slimerjs/blob/master/src/modules/webserver.jsm#L78 .

Phantom use something custom:

- js wrapper https://github.com/ariya/phantomjs/blob/master/src/modules/webserver.js#L116
- C++ part https://github.com/ariya/phantomjs/blob/master/src/webserver.cpp#L130 - it just don't care that 0 means `autodetect`.

At first glance, problem should exist in 2.0 too.

**Comment by puzrin** [comment]
Closing. Kick me if here is something important that should be kept open.
